/**
 * Generate Kraterion invite codes (KRT-XXXXXX) directly in the DB.
 *
 * Codes can ONLY be generated by us — this script (direct DB access) or the
 * admin API (`POST /admin/invites`, ADMIN_EMAILS allowlist). There is no
 * user-facing generation.
 *
 *   pnpm -F @kraterion/control-plane exec tsx scripts/generate-invites.ts \
 *     [--count N] [--max-claims M] [--note "text"] [--expires-days D] [--csv]
 *
 * Defaults: --count 1, --max-claims 1 (single-use), never expires.
 * Prints one code per line (or CSV with --csv). Retries on the rare unique
 * collision.
 */
import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { generateCode } from "../src/invites/invite-code.util.js";

interface Args {
  count: number;
  maxClaims: number;
  note: string | null;
  expiresAt: Date | null;
  csv: boolean;
}

function parseArgs(argv: string[]): Args {
  const out: Args = { count: 1, maxClaims: 1, note: null, expiresAt: null, csv: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = () => argv[++i];
    if (a === "--count") out.count = clampInt(Number(next()), 1, 500);
    else if (a === "--max-claims") out.maxClaims = clampInt(Number(next()), 1, 100_000);
    else if (a === "--note") out.note = next() ?? null;
    else if (a === "--expires-days") {
      const days = Number(next());
      if (Number.isFinite(days) && days > 0) {
        out.expiresAt = new Date(Date.now() + days * 24 * 60 * 60 * 1000);
      }
    } else if (a === "--csv") out.csv = true;
    else if (a === "-h" || a === "--help") {
      console.log(
        "usage: generate-invites.ts [--count N] [--max-claims M] [--note \"text\"] [--expires-days D] [--csv]",
      );
      process.exit(0);
    }
  }
  return out;
}

function clampInt(n: number, min: number, max: number): number {
  const v = Math.trunc(Number.isFinite(n) ? n : min);
  return Math.max(min, Math.min(max, v));
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const prisma = new PrismaClient();
  const codes: string[] = [];

  try {
    for (let i = 0; i < args.count; i++) {
      let attempts = 0;
      // Retry only on P2002 (unique collision).
      while (true) {
        attempts++;
        try {
          const row = await prisma.inviteCode.create({
            data: {
              code: generateCode(),
              max_claims: args.maxClaims,
              note: args.note,
              expires_at: args.expiresAt,
            },
            select: { code: true },
          });
          codes.push(row.code);
          break;
        } catch (err: unknown) {
          const code = (err as { code?: string }).code;
          if (code === "P2002" && attempts < 10) continue;
          throw err;
        }
      }
    }
  } finally {
    await prisma.$disconnect();
  }

  if (args.csv) {
    console.log("code,max_claims,expires_at,note");
    for (const c of codes) {
      console.log(
        [c, args.maxClaims, args.expiresAt?.toISOString() ?? "", args.note ?? ""]
          .map((v) => String(v).replace(/,/g, " "))
          .join(","),
      );
    }
  } else {
    for (const c of codes) console.log(c);
  }
  console.error(
    `\n✓ ${codes.length} code(s) generated · max_claims=${args.maxClaims}` +
      (args.expiresAt ? ` · expires ${args.expiresAt.toISOString().slice(0, 10)}` : " · no expiry"),
  );
}

main().catch((e) => {
  console.error("generate-invites failed:", e);
  process.exit(1);
});
