/**
 * Kraterion Move package — TypeScript bindings.
 *
 * The PTB-builder helpers and BCS schemas in `./generated/` are produced by
 * `@mysten/codegen` from the Move source under `move/kraterion/`. They are
 * regenerated by `pnpm --filter @kraterion/kraterion-move-sdk generate`
 * after every Move ABI change. **Do not edit files in `./generated/`
 * by hand** — they are deleted and rewritten on every codegen run.
 *
 * Layout:
 *   - `kraterion`  — re-exports the generated `kraterion::kraterion` module
 *                    (KraterionBucket, all entry functions, accessors).
 *   - `access`     — `kraterion::access::seal_approve` for Seal SDK PTB
 *                    construction.
 *   - `events`     — BCS schemas for all six emitted events.
 *   - `EVENT_TYPE` — fully-qualified `0x…::events::<Name>` strings for
 *                    `client.queryEvents({ MoveEventType: ... })`.
 *   - `parseEvent` — helper that decodes a raw event payload via the right
 *                    BCS schema based on the event's type string.
 *   - `KRATERION_PACKAGE_ID` — re-exported from `@kraterion/shared` for
 *                    convenient single-import access.
 */

import { KRATERION_PACKAGE_ID } from "@kraterion/shared";
import {
  KraterionBucketCreated,
  ApiAccessGranted,
  ApiAccessRevoked,
  BucketVisibilityChanged,
  ReserveCreated,
  ReserveCallerAuthorized,
  ReserveCallerDeauthorized,
  ReserveFunded,
  ReserveWithdrawn,
  // Pool vault events (storage-pool migration).
  KraterionVaultCreated,
  KraterionVaultRevoked,
  KraterionPooledBlobRegistered,
  KraterionPooledBlobCertified,
  KraterionPooledBlobDeleted,
  KraterionPoolExtended,
  KraterionPoolResizedGrow,
} from "./generated/kraterion/events.js";

export * as kraterion from "./generated/kraterion/kraterion.js";
export * as access from "./generated/kraterion/access.js";
export * as events from "./generated/kraterion/events.js";
export * as reserve from "./generated/kraterion/reserve.js";
export * as pool_vault from "./generated/kraterion/pool_vault.js";

export { KRATERION_PACKAGE_ID };

/** Fully-qualified event type strings, ready to pass to `client.queryEvents`. */
export const EVENT_TYPE = {
  bucketCreated: `${KRATERION_PACKAGE_ID}::events::KraterionBucketCreated`,
  apiAccessGranted: `${KRATERION_PACKAGE_ID}::events::ApiAccessGranted`,
  apiAccessRevoked: `${KRATERION_PACKAGE_ID}::events::ApiAccessRevoked`,
  bucketVisibilityChanged: `${KRATERION_PACKAGE_ID}::events::BucketVisibilityChanged`,
  reserveCreated: `${KRATERION_PACKAGE_ID}::events::ReserveCreated`,
  reserveCallerAuthorized: `${KRATERION_PACKAGE_ID}::events::ReserveCallerAuthorized`,
  reserveCallerDeauthorized: `${KRATERION_PACKAGE_ID}::events::ReserveCallerDeauthorized`,
  reserveFunded: `${KRATERION_PACKAGE_ID}::events::ReserveFunded`,
  reserveWithdrawn: `${KRATERION_PACKAGE_ID}::events::ReserveWithdrawn`,
  // Pool vault events (storage-pool migration).
  vaultCreated: `${KRATERION_PACKAGE_ID}::events::KraterionVaultCreated`,
  vaultRevoked: `${KRATERION_PACKAGE_ID}::events::KraterionVaultRevoked`,
  pooledBlobRegistered: `${KRATERION_PACKAGE_ID}::events::KraterionPooledBlobRegistered`,
  pooledBlobCertified: `${KRATERION_PACKAGE_ID}::events::KraterionPooledBlobCertified`,
  pooledBlobDeleted: `${KRATERION_PACKAGE_ID}::events::KraterionPooledBlobDeleted`,
  poolExtended: `${KRATERION_PACKAGE_ID}::events::KraterionPoolExtended`,
  poolResizedGrow: `${KRATERION_PACKAGE_ID}::events::KraterionPoolResizedGrow`,
} as const;

/**
 * Map an event's type string to the matching generated BCS schema. Used by
 * `parseEvent` and exposed for indexers that want to dispatch on type
 * themselves.
 */
const SCHEMA_BY_TYPE = {
  [EVENT_TYPE.bucketCreated]: KraterionBucketCreated,
  [EVENT_TYPE.apiAccessGranted]: ApiAccessGranted,
  [EVENT_TYPE.apiAccessRevoked]: ApiAccessRevoked,
  [EVENT_TYPE.bucketVisibilityChanged]: BucketVisibilityChanged,
  [EVENT_TYPE.reserveCreated]: ReserveCreated,
  [EVENT_TYPE.reserveCallerAuthorized]: ReserveCallerAuthorized,
  [EVENT_TYPE.reserveCallerDeauthorized]: ReserveCallerDeauthorized,
  [EVENT_TYPE.reserveFunded]: ReserveFunded,
  [EVENT_TYPE.reserveWithdrawn]: ReserveWithdrawn,
  [EVENT_TYPE.vaultCreated]: KraterionVaultCreated,
  [EVENT_TYPE.vaultRevoked]: KraterionVaultRevoked,
  [EVENT_TYPE.pooledBlobRegistered]: KraterionPooledBlobRegistered,
  [EVENT_TYPE.pooledBlobCertified]: KraterionPooledBlobCertified,
  [EVENT_TYPE.pooledBlobDeleted]: KraterionPooledBlobDeleted,
  [EVENT_TYPE.poolExtended]: KraterionPoolExtended,
  [EVENT_TYPE.poolResizedGrow]: KraterionPoolResizedGrow,
} as const;

/**
 * Parse an event's raw BCS payload into the right typed shape. Pass a
 * `parsedJson` event from a Sui RPC response (or a base64 BCS string from
 * an indexer) and the function returns one of the typed event payloads.
 *
 * Returns null if the event's type string isn't a Kraterion event — useful
 * for filtering a mixed event stream.
 */
export function parseEvent(input: {
  type: string;
  bcs?: string;
  bcsEncoding?: "base64" | "hex";
}):
  | { type: typeof EVENT_TYPE.bucketCreated; data: typeof KraterionBucketCreated.$inferType }
  | { type: typeof EVENT_TYPE.apiAccessGranted; data: typeof ApiAccessGranted.$inferType }
  | { type: typeof EVENT_TYPE.apiAccessRevoked; data: typeof ApiAccessRevoked.$inferType }
  | { type: typeof EVENT_TYPE.bucketVisibilityChanged; data: typeof BucketVisibilityChanged.$inferType }
  | { type: typeof EVENT_TYPE.reserveCreated; data: typeof ReserveCreated.$inferType }
  | { type: typeof EVENT_TYPE.reserveCallerAuthorized; data: typeof ReserveCallerAuthorized.$inferType }
  | { type: typeof EVENT_TYPE.reserveCallerDeauthorized; data: typeof ReserveCallerDeauthorized.$inferType }
  | { type: typeof EVENT_TYPE.reserveFunded; data: typeof ReserveFunded.$inferType }
  | { type: typeof EVENT_TYPE.reserveWithdrawn; data: typeof ReserveWithdrawn.$inferType }
  | { type: typeof EVENT_TYPE.vaultCreated; data: typeof KraterionVaultCreated.$inferType }
  | { type: typeof EVENT_TYPE.vaultRevoked; data: typeof KraterionVaultRevoked.$inferType }
  | { type: typeof EVENT_TYPE.pooledBlobRegistered; data: typeof KraterionPooledBlobRegistered.$inferType }
  | { type: typeof EVENT_TYPE.pooledBlobCertified; data: typeof KraterionPooledBlobCertified.$inferType }
  | { type: typeof EVENT_TYPE.pooledBlobDeleted; data: typeof KraterionPooledBlobDeleted.$inferType }
  | { type: typeof EVENT_TYPE.poolExtended; data: typeof KraterionPoolExtended.$inferType }
  | { type: typeof EVENT_TYPE.poolResizedGrow; data: typeof KraterionPoolResizedGrow.$inferType }
  | null {
  const schema = SCHEMA_BY_TYPE[input.type as keyof typeof SCHEMA_BY_TYPE];
  if (!schema || !input.bcs) return null;
  const data =
    input.bcsEncoding === "hex"
      ? schema.fromHex(input.bcs)
      : schema.fromBase64(input.bcs);
  return { type: input.type, data } as never;
}
