/**
 * Kraterion Move package — TypeScript bindings.
 *
 * The PTB-builder helpers and BCS schemas in `./generated/` are produced by
 * `@mysten/codegen` from the Move source under `move/kraterion/`. They are
 * regenerated by `pnpm --filter @kraterion/kraterion-move-sdk generate`
 * after every Move ABI change. **Do not edit files in `./generated/`
 * by hand** — they are deleted and rewritten on every codegen run.
 *
 * Layout:
 *   - `kraterion`  — re-exports the generated `kraterion::kraterion` module
 *                    (KraterionBucket, all entry functions, accessors).
 *   - `access`     — `kraterion::access::seal_approve` for Seal SDK PTB
 *                    construction.
 *   - `events`     — BCS schemas for all six emitted events.
 *   - `EVENT_TYPE` — fully-qualified `0x…::events::<Name>` strings for
 *                    `client.queryEvents({ MoveEventType: ... })`.
 *   - `parseEvent` — helper that decodes a raw event payload via the right
 *                    BCS schema based on the event's type string.
 *   - `KRATERION_PACKAGE_ID` — re-exported from `@kraterion/shared` for
 *                    convenient single-import access.
 */

import { KRATERION_PACKAGE_ID } from "@kraterion/shared";
import {
  KraterionBucketCreated,
  KraterionObjectCreated,
  KraterionObjectExtended,
  ApiAccessGranted,
  ApiAccessRevoked,
  BucketVisibilityChanged,
  ReserveCreated,
  ReserveCallerAuthorized,
  ReserveCallerDeauthorized,
  ReserveFunded,
  ReserveWithdrawn,
} from "./generated/kraterion/events.js";

export * as kraterion from "./generated/kraterion/kraterion.js";
export * as access from "./generated/kraterion/access.js";
export * as events from "./generated/kraterion/events.js";
export * as reserve from "./generated/kraterion/reserve.js";

export { KRATERION_PACKAGE_ID };

/** Fully-qualified event type strings, ready to pass to `client.queryEvents`. */
export const EVENT_TYPE = {
  bucketCreated: `${KRATERION_PACKAGE_ID}::events::KraterionBucketCreated`,
  objectCreated: `${KRATERION_PACKAGE_ID}::events::KraterionObjectCreated`,
  objectExtended: `${KRATERION_PACKAGE_ID}::events::KraterionObjectExtended`,
  apiAccessGranted: `${KRATERION_PACKAGE_ID}::events::ApiAccessGranted`,
  apiAccessRevoked: `${KRATERION_PACKAGE_ID}::events::ApiAccessRevoked`,
  bucketVisibilityChanged: `${KRATERION_PACKAGE_ID}::events::BucketVisibilityChanged`,
  reserveCreated: `${KRATERION_PACKAGE_ID}::events::ReserveCreated`,
  reserveCallerAuthorized: `${KRATERION_PACKAGE_ID}::events::ReserveCallerAuthorized`,
  reserveCallerDeauthorized: `${KRATERION_PACKAGE_ID}::events::ReserveCallerDeauthorized`,
  reserveFunded: `${KRATERION_PACKAGE_ID}::events::ReserveFunded`,
  reserveWithdrawn: `${KRATERION_PACKAGE_ID}::events::ReserveWithdrawn`,
} as const;

/**
 * Map an event's type string to the matching generated BCS schema. Used by
 * `parseEvent` and exposed for indexers that want to dispatch on type
 * themselves.
 */
const SCHEMA_BY_TYPE = {
  [EVENT_TYPE.bucketCreated]: KraterionBucketCreated,
  [EVENT_TYPE.objectCreated]: KraterionObjectCreated,
  [EVENT_TYPE.objectExtended]: KraterionObjectExtended,
  [EVENT_TYPE.apiAccessGranted]: ApiAccessGranted,
  [EVENT_TYPE.apiAccessRevoked]: ApiAccessRevoked,
  [EVENT_TYPE.bucketVisibilityChanged]: BucketVisibilityChanged,
  [EVENT_TYPE.reserveCreated]: ReserveCreated,
  [EVENT_TYPE.reserveCallerAuthorized]: ReserveCallerAuthorized,
  [EVENT_TYPE.reserveCallerDeauthorized]: ReserveCallerDeauthorized,
  [EVENT_TYPE.reserveFunded]: ReserveFunded,
  [EVENT_TYPE.reserveWithdrawn]: ReserveWithdrawn,
} as const;

/**
 * Parse an event's raw BCS payload into the right typed shape. Pass a
 * `parsedJson` event from a Sui RPC response (or a base64 BCS string from
 * an indexer) and the function returns one of the typed event payloads.
 *
 * Returns null if the event's type string isn't a Kraterion event — useful
 * for filtering a mixed event stream.
 */
export function parseEvent(input: {
  type: string;
  bcs?: string;
  bcsEncoding?: "base64" | "hex";
}):
  | { type: typeof EVENT_TYPE.bucketCreated; data: typeof KraterionBucketCreated.$inferType }
  | { type: typeof EVENT_TYPE.objectCreated; data: typeof KraterionObjectCreated.$inferType }
  | { type: typeof EVENT_TYPE.objectExtended; data: typeof KraterionObjectExtended.$inferType }
  | { type: typeof EVENT_TYPE.apiAccessGranted; data: typeof ApiAccessGranted.$inferType }
  | { type: typeof EVENT_TYPE.apiAccessRevoked; data: typeof ApiAccessRevoked.$inferType }
  | { type: typeof EVENT_TYPE.bucketVisibilityChanged; data: typeof BucketVisibilityChanged.$inferType }
  | { type: typeof EVENT_TYPE.reserveCreated; data: typeof ReserveCreated.$inferType }
  | { type: typeof EVENT_TYPE.reserveCallerAuthorized; data: typeof ReserveCallerAuthorized.$inferType }
  | { type: typeof EVENT_TYPE.reserveCallerDeauthorized; data: typeof ReserveCallerDeauthorized.$inferType }
  | { type: typeof EVENT_TYPE.reserveFunded; data: typeof ReserveFunded.$inferType }
  | { type: typeof EVENT_TYPE.reserveWithdrawn; data: typeof ReserveWithdrawn.$inferType }
  | null {
  const schema = SCHEMA_BY_TYPE[input.type as keyof typeof SCHEMA_BY_TYPE];
  if (!schema || !input.bcs) return null;
  const data =
    input.bcsEncoding === "hex"
      ? schema.fromHex(input.bcs)
      : schema.fromBase64(input.bcs);
  return { type: input.type, data } as never;
}
